import PDFDocument from "pdfkit";
import { PassThrough } from "stream";
import type { Office, LicenseRenewal } from "@shared/schema";
import {
  registerDocumentFonts,
  drawText,
  drawCentered,
  BODY,
  BODY_BOLD,
  BODY_ITALIC,
} from "./pdf-fonts";

const LINE_HEIGHT = 15;

/** Label/value row that renders an Arabic value right-to-left after the label. */
function fieldWriter(doc: PDFKit.PDFDocument, left: number) {
  return (label: string, value: string | number | null | undefined) => {
    const text = String(value ?? "").trim() || "N/A";
    const y = doc.y;

    doc.font(BODY_BOLD).fontSize(11);
    const labelText = `${label}: `;
    doc.text(labelText, left, y, { lineBreak: false });
    const valueX = left + doc.widthOfString(labelText);

    doc.font(BODY).fontSize(11);
    drawText(doc, text, valueX, y);

    doc.x = left;
    doc.y = y + LINE_HEIGHT;
  };
}

export function generateRenewalPDF(office: Office, renewal: LicenseRenewal): PassThrough {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  registerDocumentFonts(doc);

  const stream = new PassThrough();
  doc.pipe(stream);

  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;

  doc.font(BODY_BOLD).fontSize(19).text("LICENSE RENEWAL REQUEST", { align: "center" });

  doc.moveDown(0.5);
  doc.font(BODY).fontSize(13).text("Jordan Society of Tourism and Travel Agents", { align: "center" });

  doc.moveDown(1);
  doc.lineWidth(1).moveTo(left, doc.y).lineTo(right, doc.y).stroke();
  doc.moveDown(1);

  doc.font(BODY_BOLD).fontSize(12).text("OFFICE INFORMATION", { underline: true });
  doc.moveDown(0.5);

  const addField = fieldWriter(doc, left);

  addField("Office ID", office.id);
  addField("Trade Name", office.tradeNameAr);
  if (office.tradeNameEn) {
    addField("Trade Name (English)", office.tradeNameEn);
  }
  addField("Legal Name", office.legalNameRegistrar);
  addField("National Establishment Number", office.nationalEstablishmentNumber);
  addField("Social Security Number", office.socialSecurityNumber);

  doc.moveDown(0.5);

  addField("City", office.mainCity);
  addField("Area", office.mainArea);
  addField("Street", office.mainStreet);
  addField("Building Number", office.mainBuildingNumber);

  doc.moveDown(0.5);

  addField("Phone", office.phone);
  addField("Mobile", office.mobile);
  addField("Email", office.mainEmail);
  addField("Website", office.website);

  doc.moveDown(1);

  doc.font(BODY_BOLD).fontSize(12).text("RENEWAL DETAILS", left, doc.y, { underline: true });
  doc.moveDown(0.5);

  addField("Renewal ID", renewal.id);
  addField("Year", renewal.year);
  addField("Request Date", new Date(renewal.createdAt).toLocaleDateString());
  addField("Status", "Approved for Ministry Submission");

  // The closing block is laid out upward from the bottom margin so the form is
  // always a single sheet, however many name lines the office has.
  const stampBoxHeight = 80;
  const stampBoxY = doc.page.height - doc.page.margins.bottom - stampBoxHeight;
  const officialUseY = stampBoxY - 20;
  const generatedOnY = officialUseY - 22;
  const noteY = generatedOnY - 32;
  const separatorY = Math.max(doc.y + 8, noteY - 14);

  doc.lineWidth(1).moveTo(left, separatorY).lineTo(right, separatorY).stroke();

  doc.font(BODY_ITALIC).fontSize(9);
  doc.text("This document is generated by the Tourism Offices Portal.", left, noteY, {
    align: "center",
    width: right - left,
    lineBreak: false,
  });
  doc.text("Please present this document to the Ministry for approval.", left, noteY + 14, {
    align: "center",
    width: right - left,
    lineBreak: false,
  });

  doc.font(BODY).fontSize(9).text(`Generated on: ${new Date().toLocaleString()}`, left, generatedOnY, {
    align: "center",
    width: right - left,
    lineBreak: false,
  });

  doc.font(BODY_BOLD).fontSize(11).text("FOR OFFICIAL USE ONLY", left, officialUseY, {
    align: "center",
    width: right - left,
    lineBreak: false,
  });

  doc.rect(left, stampBoxY, right - left, stampBoxHeight).stroke();
  doc.font(BODY).fontSize(10).text("Ministry Stamp / Signature:", left + 10, stampBoxY + 10, {
    lineBreak: false,
  });

  doc.end();

  return stream;
}

/**
 * Certificate of membership renewal, issued once a renewal reaches FINAL_APPROVED.
 * Unlike generateRenewalPDF (which is the request the office takes to the Ministry),
 * this is the confirmation JSTA issues back to the office.
 */
export function generateRenewalCertificatePDF(office: Office, renewal: LicenseRenewal): PassThrough {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  registerDocumentFonts(doc);

  const stream = new PassThrough();
  doc.pipe(stream);

  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;
  const contentWidth = right - left;

  doc.lineWidth(2).rect(30, 30, doc.page.width - 60, doc.page.height - 60).stroke();
  doc.lineWidth(0.5).rect(38, 38, doc.page.width - 76, doc.page.height - 76).stroke();

  doc.moveDown(3);

  doc.font(BODY).fontSize(12).text("Jordan Society of Tourism and Travel Agents", {
    align: "center",
    width: contentWidth,
  });

  doc.moveDown(1.5);

  doc.font(BODY_BOLD).fontSize(24).text("CERTIFICATE OF LICENSE RENEWAL", {
    align: "center",
    width: contentWidth,
  });

  doc.moveDown(0.5);
  doc.font(BODY).fontSize(14).text(`Year ${renewal.year}`, { align: "center", width: contentWidth });

  doc.moveDown(2);
  doc.lineWidth(1).moveTo(left + 40, doc.y).lineTo(right - 40, doc.y).stroke();
  doc.moveDown(2);

  doc.font(BODY).fontSize(12);
  doc.text("This is to certify that the tourism office named below has completed its", {
    align: "center",
    width: contentWidth,
  });
  doc.text(`license renewal for the year ${renewal.year}, and that the renewal has been`, {
    align: "center",
    width: contentWidth,
  });
  doc.text("finally approved.", { align: "center", width: contentWidth });

  doc.moveDown(2);

  const arabicName = office.tradeNameAr;
  const englishName = office.tradeNameEn || office.legalNameRegistrar;

  if (arabicName) {
    doc.font(BODY_BOLD).fontSize(18);
    drawCentered(doc, arabicName, left, right, doc.y);
    doc.y += 26;
  }

  if (englishName) {
    doc.font(arabicName ? BODY : BODY_BOLD).fontSize(arabicName ? 12 : 18);
    drawCentered(doc, englishName, left, right, doc.y);
    doc.y += 20;
  }

  if (!arabicName && !englishName) {
    doc.font(BODY_BOLD).fontSize(18);
    drawCentered(doc, `Office #${office.id}`, left, right, doc.y);
    doc.y += 20;
  }

  doc.moveDown(2);
  doc.x = left;

  const addField = fieldWriter(doc, left + 60);

  addField("Registration Number", office.registrationNumber);
  addField("License Category", office.licenseCategory);
  addField("National Establishment Number", office.nationalEstablishmentNumber);
  addField("City", office.mainCity);
  addField("Renewal Reference", `${renewal.year}-${renewal.id}`);
  addField("Approved On", new Date(renewal.updatedAt || renewal.createdAt).toLocaleDateString());

  // Anchor the signature row to the lower third so the certificate is one page
  // regardless of how many name lines the office has.
  const signatureY = Math.max(doc.y + 30, doc.page.height - 200);
  doc.lineWidth(0.8).moveTo(left + 60, signatureY).lineTo(left + 240, signatureY).stroke();
  doc.font(BODY).fontSize(10).text("Authorized Signature", left + 60, signatureY + 6, {
    lineBreak: false,
  });

  doc.lineWidth(0.8).moveTo(right - 240, signatureY).lineTo(right - 60, signatureY).stroke();
  doc.font(BODY).fontSize(10).text("Official Stamp", right - 240, signatureY + 6, {
    lineBreak: false,
  });

  doc.font(BODY_ITALIC).fontSize(9).text(
    `Issued by the Tourism Offices Portal on ${new Date().toLocaleDateString()}.`,
    left + 40,
    signatureY + 55,
    { align: "center", width: contentWidth - 80, lineBreak: false }
  );
  doc.text(
    `Verify with JSTA using reference ${renewal.year}-${renewal.id}.`,
    left + 40,
    signatureY + 69,
    { align: "center", width: contentWidth - 80, lineBreak: false }
  );

  doc.end();

  return stream;
}
