import PDFDocument from "pdfkit";
import { PassThrough } from "stream";
import type { Office, LicenseRenewal } from "@shared/schema";

export function generateRenewalPDF(office: Office, renewal: LicenseRenewal): PassThrough {
  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
  });

  const stream = new PassThrough();
  doc.pipe(stream);

  doc.fontSize(20)
    .font("Helvetica-Bold")
    .text("LICENSE RENEWAL REQUEST", { align: "center" });
  
  doc.moveDown();
  doc.fontSize(14)
    .font("Helvetica")
    .text("Jordan Society of Tourism Agents", { align: "center" });
  
  doc.moveDown(2);
  
  doc.lineWidth(1)
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .stroke();
  
  doc.moveDown(2);

  doc.fontSize(12)
    .font("Helvetica-Bold")
    .text("OFFICE INFORMATION", { underline: true });
  
  doc.moveDown();
  doc.font("Helvetica");
  
  const addField = (label: string, value: string | number | null | undefined) => {
    doc.font("Helvetica-Bold").text(`${label}: `, { continued: true });
    doc.font("Helvetica").text(String(value || "N/A"));
    doc.moveDown(0.5);
  };

  addField("Office ID", office.id);
  addField("Trade Name", office.tradeNameAr);
  addField("Legal Name", office.legalNameRegistrar);
  addField("National Establishment Number", office.nationalEstablishmentNumber);
  addField("Social Security Number", office.socialSecurityNumber);
  
  doc.moveDown();
  
  addField("City", office.mainCity);
  addField("Area", office.mainArea);
  addField("Street", office.mainStreet);
  addField("Building Number", office.mainBuildingNumber);
  
  doc.moveDown();
  
  addField("Phone", office.phone);
  addField("Mobile", office.mobile);
  addField("Email", office.mainEmail);
  addField("Website", office.website);

  doc.moveDown(2);

  doc.fontSize(12)
    .font("Helvetica-Bold")
    .text("RENEWAL DETAILS", { underline: true });
  
  doc.moveDown();
  doc.font("Helvetica");
  
  addField("Renewal ID", renewal.id);
  addField("Year", renewal.year);
  addField("Request Date", new Date(renewal.createdAt).toLocaleDateString());
  addField("Status", "Approved for Ministry Submission");

  doc.moveDown(2);

  doc.lineWidth(1)
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .stroke();
  
  doc.moveDown(2);

  doc.fontSize(10)
    .font("Helvetica-Oblique")
    .text("This document is generated by the Tourism Offices Portal.", { align: "center" });
  doc.text("Please present this document to the Ministry for approval.", { align: "center" });
  
  doc.moveDown(2);

  doc.fontSize(10)
    .font("Helvetica")
    .text(`Generated on: ${new Date().toLocaleString()}`, { align: "center" });

  doc.moveDown(4);

  doc.fontSize(11)
    .font("Helvetica-Bold")
    .text("FOR OFFICIAL USE ONLY", { align: "center" });
  
  doc.moveDown();

  doc.rect(50, doc.y, 495, 100)
    .stroke();
  
  doc.moveDown();
  doc.fontSize(10)
    .font("Helvetica")
    .text("Ministry Stamp / Signature:", 60, doc.y + 10);

  doc.end();

  return stream;
}
